/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import static View.CPU.falsoCLS;
import static View.CPU.getpJog;
import static View.CPU.getvXO;
import static View.CPU.iniciarTabuleiro;
import static View.CPU.mostraTabuleiro;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LSA
 */
public class Cpartida2 extends javax.swing.JFrame {
    static int s1=0;
    static int s2=0;
    static String nome ;
    /**
     * Creates new form NewJFrame
     */
    public Cpartida2() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagem/logo.png")).getImage());
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        cNome1 = new javax.swing.JTextField();
        VE2 = new javax.swing.JRadioButton();
        PVc2 = new javax.swing.JRadioButton();
        PV2 = new javax.swing.JRadioButton();
        VXJO1 = new javax.swing.JRadioButton();
        VOJX1 = new javax.swing.JRadioButton();
        VE3 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cNome = new javax.swing.JTextField();
        VE = new javax.swing.JRadioButton();
        PVc = new javax.swing.JRadioButton();
        PV = new javax.swing.JRadioButton();
        VXJO = new javax.swing.JRadioButton();
        VOJX = new javax.swing.JRadioButton();
        VE1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Bcancelar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        bOK = new javax.swing.JButton();
        cNome2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cNome1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNome1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(VE2);
        VE2.setText("Velha Escolhe");
        VE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VE2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(PVc2);
        PVc2.setText("Você");
        PVc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PVc2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(PV2);
        PV2.setText("Velha");

        buttonGroup1.add(VXJO1);
        VXJO1.setText("Velha(X) e Você(O)");
        VXJO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VXJO1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(VOJX1);
        VOJX1.setText("Velha(O) e Você(X)");
        VOJX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOJX1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(VE3);
        VE3.setText("Velha Escolhe");

        jLabel4.setText("X ou O?");

        jLabel5.setText("Quem Joga Primeiro?");

        jLabel6.setText("Seu nome?");

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VE2)
                            .addComponent(PVc2)
                            .addComponent(PV2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addComponent(VE3)
                                .addComponent(VOJX1)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(cNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                .addComponent(jSeparator4)
                                .addComponent(VXJO1)))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VXJO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VOJX1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VE3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PV2)
                .addGap(3, 3, 3)
                .addComponent(PVc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VE2)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Partida");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNomeActionPerformed(evt);
            }
        });

        buttonGroup2.add(VE);
        VE.setText("Velha Escolhe");
        VE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEActionPerformed(evt);
            }
        });

        buttonGroup2.add(PVc);
        PVc.setText("Segundo Jogado");
        PVc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PVcActionPerformed(evt);
            }
        });

        buttonGroup2.add(PV);
        PV.setText("Primeiro Jogado");

        buttonGroup1.add(VXJO);
        VXJO.setText("Primeiro Jogador(X) e Segundo Jogador(O)");
        VXJO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VXJOActionPerformed(evt);
            }
        });

        buttonGroup1.add(VOJX);
        VOJX.setText("Primeiro Jogador(O) e Segundo Jogador(X)");
        VOJX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOJXActionPerformed(evt);
            }
        });

        buttonGroup1.add(VE1);
        VE1.setText("Velha Escolhe");

        jLabel1.setText("X ou O?");

        jLabel2.setText("Quem Joga Primeiro?");

        jLabel3.setText("Nome do Segundo Jogador:");

        Bcancelar.setText("Cancelar");
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Configurando Partida: Dois Jogadores");

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        cNome2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNome2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome do Primeiro Jogador:");

        jButton5.setText("Voltar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(VE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PVc)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(VE1)
                                .addComponent(VOJX)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(cNome, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                .addComponent(jSeparator2)
                                .addComponent(VXJO)
                                .addComponent(jSeparator6)
                                .addComponent(cNome2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(Bcancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(PV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(cNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VXJO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VOJX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PVc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcancelar)
                    .addComponent(bOK)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNomeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cNomeActionPerformed

    private void VEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VEActionPerformed

    private void PVcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PVcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PVcActionPerformed

    private void VXJOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VXJOActionPerformed

    }//GEN-LAST:event_VXJOActionPerformed

    private void VOJXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOJXActionPerformed

    }//GEN-LAST:event_VOJXActionPerformed

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
            this.dispose();
    }//GEN-LAST:event_BcancelarActionPerformed

    private void cNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNome1ActionPerformed

    private void VE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VE2ActionPerformed

    private void PVc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PVc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PVc2ActionPerformed

    private void VXJO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VXJO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VXJO1ActionPerformed

    private void VOJX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOJX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VOJX1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed

        Random rand = new Random();
        int test;
        
 if ((cNome.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Campo vazio");
        } else {
                    
                    nome=(cNome.getText());
                    JOptionPane.showMessageDialog(null, "Matéria " +cNome.getText() + " inserida com sucesso! ");
                    cNome.setText("");
                    
                }


  
  
        

        if (VXJO.isSelected()) {
            CPU.setvXO("X");
            CPU.setjXO("O");
            System.out.print(CPU.getvXO());
            System.out.print(CPU.getjXO());
            s1=1;
            
        } else if (VOJX.isSelected()) {
            CPU.setvXO("O");
            CPU.setjXO("X");
            System.out.print(CPU.getvXO());
            System.out.print(CPU.getjXO());
            s1=2;
          
        } else if (VE1.isSelected()) {
            test = rand.nextInt(2);
            if (test == 1) {
                CPU.setvXO("O");
                CPU.setjXO("X");
                System.out.print(CPU.getvXO());
                System.out.print(CPU.getjXO());
                System.out.print(test);
             s1=3;
                
            } else {
                CPU.setvXO("X");
                CPU.setjXO("O");
                System.out.print(CPU.getvXO());
                System.out.print(CPU.getjXO());
               s1=3;
                
                System.out.print(test);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo vazio");

        }

 
 
        
        Tabuleiro t = new Tabuleiro();

        
        
                
        if (PV.isSelected()) {
            CPU.setpJog(CPU.getvXO());
            CPU.setP(CPU.getvXO());
            s2=1;
            t.setVisible(true);
            this.dispose();
            System.out.println(CPU.getpJog());
        } else if (PVc.isSelected()) {
            CPU.setpJog(CPU.getjXO());
            CPU.setP(CPU.getjXO());
            s2=2;
            t.setVisible(true);
            this.dispose();
            System.out.println(CPU.getpJog());
        } else if (VE.isSelected()) {
            test = rand.nextInt(2);
            if (test == 1) {
                CPU.setpJog(CPU.getjXO());
                CPU.setP(CPU.getjXO());
                s2=3;
                t.setVisible(true);
                this.dispose();
                System.out.print(test);
                System.out.println(CPU.getpJog());

            } else {
                CPU.setpJog(CPU.getvXO());
                CPU.setP(CPU.getvXO());
                s2=3;
                t.setVisible(true);
                this.dispose();
                System.out.print(test);
                System.out.println(CPU.getpJog());
            }
        } else {

            JOptionPane.showMessageDialog(null, "Campo vazio");

        }

        CPU.iniciarTabuleiro();
        CPU.falsoCLS();
        CPU.mostraTabuleiro();

        if (CPU.getpJog().equals(CPU.getvXO())) {
            CPU.velhaJoga();

        }

    }//GEN-LAST:event_bOKActionPerformed

    private void cNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNome2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TInicial t = new TInicial();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cpartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cpartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cpartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cpartida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cpartida2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancelar;
    public static javax.swing.JRadioButton PV;
    private javax.swing.JRadioButton PV2;
    public static javax.swing.JRadioButton PVc;
    private javax.swing.JRadioButton PVc2;
    public javax.swing.JRadioButton VE;
    public javax.swing.JRadioButton VE1;
    private javax.swing.JRadioButton VE2;
    private javax.swing.JRadioButton VE3;
    public javax.swing.JRadioButton VOJX;
    private javax.swing.JRadioButton VOJX1;
    public javax.swing.JRadioButton VXJO;
    private javax.swing.JRadioButton VXJO1;
    private javax.swing.JButton bOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JTextField cNome;
    private javax.swing.JTextField cNome1;
    public static javax.swing.JTextField cNome2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
