# Project: Projeto1
# Makefile created by Dev-C++ 5.8.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o questao_tipo2.o
LINKOBJ  = main.o questao_tipo2.o
LIBS     = -L"C:/Development/Dev-Cpp/MinGW64/lib" -L"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Development/Dev-Cpp/MinGW64/include" -I"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Development/Dev-Cpp/MinGW64/include" -I"C:/Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Projeto1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

questao_tipo2.o: questao_tipo2.c
	$(CC) -c questao_tipo2.c -o questao_tipo2.o $(CFLAGS)
